import { useState, useEffect } from 'react';
import { RotateCw, ChevronLeft, ChevronRight, Sparkles, Loader2 } from 'lucide-react';
import { flashcardService } from '../services/flashcardService';
import { aiService } from '../services/aiService';
import { lessonService } from '../services/lessonService';
import { Flashcard as FlashcardType } from '../types';

export default function Flashcards() {
  const [selectedSubject, setSelectedSubject] = useState('science');
  const [selectedClass, setSelectedClass] = useState('6');
  const [selectedChapter, setSelectedChapter] = useState('');
  const [hasGenerated, setHasGenerated] = useState(false);
  const [currentCardIndex, setCurrentCardIndex] = useState(0);
  const [flippedCards, setFlippedCards] = useState<Record<number, boolean>>({});
  const [flashcards, setFlashcards] = useState<FlashcardType[]>([]);
  const [isLoading, setIsLoading] = useState(false);

  const subjects = [
    { value: 'science', label: 'Science' },
    { value: 'mathematics', label: 'Mathematics' },
    { value: 'social-science', label: 'Social Science' }
  ];

  const chapters: Record<string, string[]> = {
    'science-6': ['Food – Where Does It Come From?', 'Components of Food', 'Fibre to Fabric'],
    'science-7': ['Nutrition in Plants', 'Nutrition in Animals', 'Heat'],
    'science-8': ['Crop Production', 'Microorganisms', 'Coal and Petroleum']
  };

  const getChapters = () => {
    return chapters[`${selectedSubject}-${selectedClass}`] || [];
  };

  useEffect(() => {
    loadAllFlashcards();
  }, []);

  const loadAllFlashcards = async () => {
    setIsLoading(true);
    try {
      const allCards = await flashcardService.getAllFlashcards();
      setFlashcards(allCards);
      if (allCards.length > 0) {
        setHasGenerated(true);
      }
    } catch (error) {
      console.error('Error loading flashcards:', error);
    } finally {
      setIsLoading(false);
    }
  };

  const handleGenerate = async () => {
    if (!selectedChapter) {
      alert('Please select a chapter');
      return;
    }

    setIsLoading(true);
    try {
      const topic = `${selectedSubject} Class ${selectedClass} ${selectedChapter}`;
      const flashcardData = await aiService.generateFlashcardsForTopic(topic);

      const lesson = await lessonService.createLesson({
        title: topic,
        subject: selectedSubject,
        content: `Flashcards for ${topic}`,
        summary: [`Study cards for ${selectedChapter}`],
      });

      await flashcardService.createMultipleFlashcards(lesson.id, flashcardData);

      await loadAllFlashcards();
      setHasGenerated(true);
      setCurrentCardIndex(0);
      setFlippedCards({});
      alert(`✅ Generated ${flashcardData.length} flashcards for ${topic}!`);
    } catch (error) {
      console.error('Flashcard generation error:', error);
      alert('⚠️ Error generating flashcards. Please check your API configuration.');
    } finally {
      setIsLoading(false);
    }
  };

  const handleFlip = (cardId: number) => {
    setFlippedCards(prev => ({ ...prev, [cardId]: !prev[cardId] }));
  };

  const handlePrevious = () => {
    if (currentCardIndex > 0) {
      setCurrentCardIndex(currentCardIndex - 1);
    }
  };

  const handleNext = () => {
    if (currentCardIndex < flashcards.length - 1) {
      setCurrentCardIndex(currentCardIndex + 1);
    }
  };

  const currentCard = flashcards[currentCardIndex];
  const isFlipped = currentCard ? (flippedCards[currentCardIndex] || false) : false;

  return (
    <div className="min-h-screen bg-gradient-to-br from-pink-50 via-purple-50 to-indigo-50 py-12">
      <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="text-center mb-12">
          <div className="inline-block mb-4">
            <div className="bg-gradient-to-r from-pink-500 to-purple-500 text-white px-4 py-2 rounded-full text-sm font-medium flex items-center gap-2">
              <Sparkles className="w-4 h-4" />
              <span>AI-Generated Flashcards</span>
            </div>
          </div>
          <h1 className="text-4xl md:text-5xl font-bold text-gray-900 mb-4">
            Flashcards for Easy Revision
          </h1>
          <p className="text-xl text-gray-600">
            Quick recall questions generated by AI.
          </p>
        </div>

        <div className="bg-white rounded-2xl shadow-xl p-8 mb-8">
          <h2 className="text-2xl font-bold text-gray-900 mb-6">Select Your Topic</h2>

          <div className="grid md:grid-cols-3 gap-6 mb-6">
            <div>
              <label className="block text-sm font-semibold text-gray-700 mb-2">
                Subject
              </label>
              <select
                value={selectedSubject}
                onChange={(e) => {
                  setSelectedSubject(e.target.value);
                  setSelectedChapter('');
                  setHasGenerated(false);
                }}
                className="w-full px-4 py-3 border-2 border-gray-200 rounded-xl focus:border-purple-500 focus:ring-2 focus:ring-purple-200 outline-none transition-all"
              >
                {subjects.map((subject) => (
                  <option key={subject.value} value={subject.value}>
                    {subject.label}
                  </option>
                ))}
              </select>
            </div>

            <div>
              <label className="block text-sm font-semibold text-gray-700 mb-2">
                Class
              </label>
              <select
                value={selectedClass}
                onChange={(e) => {
                  setSelectedClass(e.target.value);
                  setSelectedChapter('');
                  setHasGenerated(false);
                }}
                className="w-full px-4 py-3 border-2 border-gray-200 rounded-xl focus:border-purple-500 focus:ring-2 focus:ring-purple-200 outline-none transition-all"
              >
                {[6, 7, 8, 9, 10].map((cls) => (
                  <option key={cls} value={cls}>
                    Class {cls}
                  </option>
                ))}
              </select>
            </div>

            <div>
              <label className="block text-sm font-semibold text-gray-700 mb-2">
                Chapter
              </label>
              <select
                value={selectedChapter}
                onChange={(e) => {
                  setSelectedChapter(e.target.value);
                  setHasGenerated(false);
                }}
                className="w-full px-4 py-3 border-2 border-gray-200 rounded-xl focus:border-purple-500 focus:ring-2 focus:ring-purple-200 outline-none transition-all"
              >
                <option value="">Select a chapter</option>
                {getChapters().map((chapter, idx) => (
                  <option key={idx} value={chapter}>
                    {chapter}
                  </option>
                ))}
              </select>
            </div>
          </div>

          <button
            onClick={handleGenerate}
            disabled={!selectedChapter}
            className="w-full bg-gradient-to-r from-pink-600 to-purple-600 text-white py-4 rounded-xl font-semibold text-lg hover:from-pink-700 hover:to-purple-700 transition-all disabled:opacity-50 disabled:cursor-not-allowed shadow-lg hover:shadow-xl"
          >
            Generate Flashcards
          </button>
        </div>

        {hasGenerated && (
          <>
            <div className="mb-8">
              <div className="flex items-center justify-between mb-6">
                <p className="text-lg font-semibold text-gray-700">
                  Card {currentCardIndex + 1} of {demoFlashcards.length}
                </p>
                <button
                  onClick={handleGenerate}
                  className="flex items-center gap-2 bg-purple-100 text-purple-700 px-4 py-2 rounded-lg hover:bg-purple-200 transition-all font-medium"
                >
                  <RotateCw className="w-4 h-4" />
                  Generate More
                </button>
              </div>

              <div className="relative">
                <div className="perspective-1000">
                  <div
                    onClick={() => handleFlip(currentCard.id)}
                    className={`relative w-full h-80 cursor-pointer transition-transform duration-500 transform-style-3d ${
                      isFlipped ? 'rotate-y-180' : ''
                    }`}
                  >
                    <div className="absolute inset-0 backface-hidden">
                      <div className="h-full bg-gradient-to-br from-pink-500 to-purple-600 rounded-2xl shadow-2xl p-12 flex items-center justify-center text-center">
                        <div>
                          <p className="text-sm text-white/80 mb-4 font-medium uppercase tracking-wider">
                            Question
                          </p>
                          <p className="text-3xl md:text-4xl font-bold text-white leading-relaxed">
                            {currentCard.front}
                          </p>
                          <p className="text-sm text-white/70 mt-8">
                            Tap to reveal answer
                          </p>
                        </div>
                      </div>
                    </div>

                    <div
                      className="absolute inset-0 backface-hidden rotate-y-180"
                    >
                      <div className="h-full bg-gradient-to-br from-indigo-500 to-blue-600 rounded-2xl shadow-2xl p-12 flex items-center justify-center text-center">
                        <div>
                          <p className="text-sm text-white/80 mb-4 font-medium uppercase tracking-wider">
                            Answer
                          </p>
                          <p className="text-2xl md:text-3xl font-bold text-white leading-relaxed">
                            {currentCard.back}
                          </p>
                          <p className="text-sm text-white/70 mt-8">
                            Tap to see question
                          </p>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>

                <div className="flex items-center justify-between mt-8">
                  <button
                    onClick={handlePrevious}
                    disabled={currentCardIndex === 0}
                    className="flex items-center gap-2 bg-white text-gray-700 px-6 py-3 rounded-xl font-semibold hover:bg-gray-50 transition-all disabled:opacity-30 disabled:cursor-not-allowed shadow-lg"
                  >
                    <ChevronLeft className="w-5 h-5" />
                    Previous
                  </button>

                  <div className="flex gap-2">
                    {demoFlashcards.map((_, idx) => (
                      <button
                        key={idx}
                        onClick={() => setCurrentCardIndex(idx)}
                        className={`w-3 h-3 rounded-full transition-all ${
                          idx === currentCardIndex
                            ? 'bg-purple-600 w-8'
                            : 'bg-gray-300 hover:bg-gray-400'
                        }`}
                      />
                    ))}
                  </div>

                  <button
                    onClick={handleNext}
                    disabled={currentCardIndex === demoFlashcards.length - 1}
                    className="flex items-center gap-2 bg-white text-gray-700 px-6 py-3 rounded-xl font-semibold hover:bg-gray-50 transition-all disabled:opacity-30 disabled:cursor-not-allowed shadow-lg"
                  >
                    Next
                    <ChevronRight className="w-5 h-5" />
                  </button>
                </div>
              </div>
            </div>

            <div className="bg-white rounded-2xl shadow-xl p-8">
              <h3 className="text-2xl font-bold text-gray-900 mb-6">All Flashcards</h3>
              <div className="grid sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-4">
                {demoFlashcards.map((card, idx) => (
                  <button
                    key={card.id}
                    onClick={() => setCurrentCardIndex(idx)}
                    className={`p-4 rounded-xl border-2 transition-all text-left ${
                      idx === currentCardIndex
                        ? 'border-purple-500 bg-purple-50'
                        : 'border-gray-200 hover:border-purple-300 hover:bg-gray-50'
                    }`}
                  >
                    <p className="text-xs text-gray-500 font-semibold mb-2">Card {idx + 1}</p>
                    <p className="text-sm font-medium text-gray-900 line-clamp-2">
                      {card.front}
                    </p>
                  </button>
                ))}
              </div>
            </div>
          </>
        )}
      </div>

      <style>{`
        .perspective-1000 {
          perspective: 1000px;
        }
        .transform-style-3d {
          transform-style: preserve-3d;
        }
        .backface-hidden {
          backface-visibility: hidden;
        }
        .rotate-y-180 {
          transform: rotateY(180deg);
        }
      `}</style>
    </div>
  );
}
